language: java
jdk:
- oraclejdk10
- oraclejdk8
- openjdk7
#- oraclejdk7
#- openjdk6
env:
  global:
  - SONATYPE_USERNAME=daniel_peintner
  - secure: "qXwiaxDVsMsp+1OX+HGaYR6NuZYnxKkDbEI5GTczgVm/8DIJ0Ioyu4V79/SUFiUdLrtE8ze/tcvForAZFEho5w1O/MsUyctX9IMHz+QltMDYJSf1hoFtbyJE+b+AKWQCAaBvDMORk+mK6S3CaRPkODaMmF4DvtDCNtIfcMKx7KEdXhkf0otKeMtBJPh0WsMkwYZrKNvX4SuzJa0LzYRlDdYWKyL4wusKH1AkD5x47Tu/9IycW4uIxIMiSwBtBEQ0Wugx9hnQIItbBay09ZYxItP779YmLmzA6SHdsv4h6//1qvLJFAQq8NYs3CB8BNAFOz0e/yB4hNL25v2ZiTEL3CWuf030EtY+4CL5W8zsY7q2XKKs3X64NTk1/Tu+U9RNQ7HkHmwVYRNA96Tv2JFsBp8Uo5HIoAPEshOU4IYgUOUPBTZ5wcyLck4g630dvUMdi+vzmRIBS08FhsLvMDnB62vNb4fudfqGTpk0L619bWaIzamM+42JTTYdkPdukk0Mn04q0oHJNEyFARLG4tBpmj9Vq6iNLgtYMNCTpqloQR1tYyY3F/L/oWMG86ZonGORFmhP0SsgHFWTfpNgE1IAA3eQoEy4X0vgn2md+snA7DFE+qHovgo5SHTapfG4Na4m0RO89IpsnWUiCu0JZodwY1asokPcURY84Tkjd+w/smI="
after_success:
  - mvn deploy --settings settings.xml -DskipTests=true -B
  
